"""Galerkin-supervised autonomous neural flows."""

from ngfield import (
    Coefficient,
    Function,
    Geometry,
    MeanZero,
    Periodic,
    Solution,
    Space,
    State,
    ZeroTrace,
    contract,
    cos,
    div,
    dot,
    exp,
    grad,
    inner,
    log,
    outer,
    pointwise,
    sin,
    sqrt,
    stack,
    sym_grad,
    tanh,
    trace,
    transpose,
)

from .problem import NeuralSemigroupProblem
from .semigroup import NeuralSemigroup
from .workflow import Evaluation, FieldReport, Model, System, TrajectoryReport

__version__ = "0.1.0"
__all__ = [
    "Evaluation",
    "Coefficient",
    "FieldReport",
    "Function",
    "Geometry",
    "MeanZero",
    "Model",
    "NeuralSemigroup",
    "NeuralSemigroupProblem",
    "Periodic",
    "Solution",
    "Space",
    "State",
    "System",
    "TrajectoryReport",
    "ZeroTrace",
    "contract",
    "cos",
    "div",
    "dot",
    "exp",
    "grad",
    "inner",
    "log",
    "outer",
    "pointwise",
    "sin",
    "sqrt",
    "stack",
    "sym_grad",
    "tanh",
    "trace",
    "transpose",
]
